namespace WhyNotLang.Tokenizer
{
    public enum TokenType
    {
        Identifier,
        String,
        Number,
        Var,
        Begin,
        End,
        If,
        Else,
        While,
        Function,
        Return,
        LeftParen,
        RightParen,
        Plus,
        Minus,
        Multiply,
        Divide,
        Assign,
        Not,
        LessThan,
        GreaterThan,
        LessThanOrEqual,
        GreaterThanOrEqual,
        Equal,
        NotEqual,
        Invalid,
        Eof
    }
}