dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 3.1
script:
#- "./scripts/install-dotnet.sh"
- "./scripts/run-tests.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: s3
  access_key_id: AKIAUBRS2K73MCPSHBK4
  secret_access_key:
    secure: XIzSvDYZCNZv4td5ve9jDMaGBkRastg6w0DMMBFg+g/p5toLazqa1mGmYCe4QO2Vs6FsAR8pXgbMMocEDtf10eAw33b7pusDkGWYnt7dx/G2gWdsXVBV48nsZ5ucD0ZzhWRPITJW55GGimSBdDgkxz/X15iZMxP47cL4HGRryOBxcoJthmLuQlF3nuHUMjTpldG39/7nn42NYceEmlmXFI5d2uuQ0AVCrkmKye0yT+CbO1/yZStgsWz6APM3KGcxURhaM5a7B3TgWltsBKQJfOasah0OuSJiujkdAYg0xu2pr98eQyJ859pttxJoMWQI6NdPSZyD05Ij5Qy2gWvLcmoWPAg+Yaf41T2mKwQX+qbi8ZRwc70A0YuPSfcNzRfoKV/EeSTW3AvU3gt/qPzyMkyu8bz5BU5/JgA0IJ24HLjrNnDwxPwYfifW1q2H9BuQHURepDhcEDWfgz7xWVDfT60qLzN2VfA1r2U8tDw98cWhUi44qvT4uu9hx7wyofNKBK7Kh0W/6IkrDv72Ve7pe0KQswDsalIRVbupiqU8QAvLFPIChngZekfpQYTPDtt5Z82TaWI+QlGr3sZLLujpNboWjv7pCcMRZp439/aCL673R782Vo09FWk7VnVeAWl61IGqoOIlrRABV2thNnb3opJAQcage/EXIeZWTyyrntU=
  bucket: whynotlang-2021
  region: eu-west-1
  local-dir: artifacts
  skip_cleanup: true
  acl: public_read
  on:
    repo: pkedziora/whynotlang
