dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 3.1
script:
- "./scripts/run-tests.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: s3
  access_key_id: AKIAUBRS2K73MCPSHBK4
  secret_access_key:
    secure: f1ztNbdqOZtYwVMM/m4ASwtWDaleBxTKnTK6vei72KkD+X1aoswwL9bpeIHaxaQ+NzwLHZYCQgSGOGNMAsJ/GpwVVoHl5y9tVprfe620OhRQp7qNt85GsutDcvZpkQAtnEc7ndPO/hh3uY2E/Sm0KV4irUV0lxqQn5rQDeJJW2YhDS1T43By6P6ROcJPvkwDpZ15e1OXXagku4DojRYBeJvxpvnLMVW4ekdtBng7ElBtVGAG7+q7DptxZUOxT60Uk23otdJR/lrxrJAMYXFnBSyAcw9Z1Agg21EsuBgQUU/hb9seOOsSOuw5Ja0F7O8I3tvgslgHnRq1IolnIXXNg1SQpoXDIWp0lRe5zHTWiIxys1gICY5rIjpn9720jbum5lZZIxUC3b/LApVVdf3kRu64iVRkuWUeCbptic0XVKcC3kYCWlrS3PfEuHPfwofiQSSykGn91ujFaTrRkKep3bmst5PFA3F+DU25hEr6sPbRoiogrIkgOi/DPCFxdSAMLu9SINJIoSHOkfapgHpsVRgnjgTkJqIZRw6pq4hVqJ8tsbYc2NKIAH1yGPerE9XInc+yzLQi3diqm9lD0agdvQ3EoYoPbfadtf/7kpkUCILfeGy2VvOUrevFNuCgq71QgSOADvjfhc7y9leBhEn+7bKti1Ysq/0XzLzWm0k61YI=
  bucket: whynotlang-2021
  region: eu-west-1
  local-dir: artifacts
  skip_cleanup: true
  acl: public_read
  on:
    repo: pkedziora/whynotlang
env:
  global:
    secure: UQw3G9fJcDZ5wWwLWcDBdWNMqHpEkRqSIyUQPhOEbSTbHkCdM4PVuo7W4khE1j0rZmstiKUnJKTCy8IpcN0W+aL32VHkVBcl4yE1OybY4jq91Z39qO8omBrOoDh1BHyz3AAXOIGTPSyeI9SCxRvuyIzj8pngCzyiXrifyzS0dRK0i0SxGClOW52ygQnyA2tiO5ZpzSS9655UXEjCW8Y8sruLsbCrZQmfMKeumR3QZriovKDrbUzjTOglPooKoSB0Tw7xMS3Qh6QzdYblie90mji7HdQO95iz0fT4i695Q4Xd9uf0MktyK2tSWaGWUG6eiPMSP6lRbaxj8F2uQtEMdwuPY+dWnQjJ/kOxj/EYhQ+0e2d5LQY2TVxdeRQrkslJk0Du7WpQFF1/+oQ/32AZzODhxNJNT0p/3Zg/aM69Ki4xPLi4gK4o2ceoR8+haUnHAa0qI2erTbhVOXST8/vyR3RA64T2JUivcrdjkNg52RknQm4GJW+i4lCdu+vAhYiwB/s+ao523UydUfOQokI/lPR81n1feOWluI4yuGtPqnNVxxnIORb8xg4DuTlPRHD58mVj0qewb4oLcuQnKbk12l/4KRHrAP02AkHQb7BYcgJqnQVhNmMWKzETHBDnZFTiwH5SH5muKpbIvg78qSdEjPLf4SISDfdn9D+2CkrHRI0=
