dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 2.2.401
script:
- "./scripts/install-dotnet.sh"
- "./scripts/run-tests.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: s3
  access_key_id: AKIAVQZTVZS35D2ES3LE
  secret_access_key:
    secure: k43rlcC4wIBnY/9zmNLr8ECKEzal9y8pteQr/Dv20fFWiHFhetX5nDRGjzLoxJfRWCDHaWuoYvLnQ1x0OEWYIAvZdgqKVY2euo8c+tkY3qJydUor5fINkqylMW76Q0VyohHeyhxFYrWSA2fmHomfoJYESSq64aJv5yrhhr4i9/YrP7Ughq879iJsXGwkk3yxIif5ijUYroDVOfHHQPZ6FSxcoGQepO3wcNV3q7HbaG+8LQHrlZXd+/8kKQtJ876NIb7FHFixAPSKgiLZEI9z35NBIGpj3nlFnyCNb4efS53l3ZUuIZhHxED3NwV4ftm2vtU8cvJJHGL9mx8DTSzYUGte7MVzhq6QjdzzlAVhmAGxtXj0H8XMYLNQaDJ4Qdmy+qGIyGfV6B7zGPv2YYz++eAYiZ1+eGJ2DJKla1+FLYFOHwnkFJGuwiRb4t6VNGekGWfcki8++tWpzEgNFrLtx1EWV/kTmBI2DninRgK87Pbt0u1VRL9c3K7ATuyX7Vdn00/JtvZ4Rn+lD2JTxons0WgmxhDae3W61rOplpKH0rPo55FUH4auTmeS0B0agyu/YnvV75R2aHjt2gYLylDE2QTudlIbZ0GhqS8azXL0NRFgp+svQySGNII6xG8kLIKFyA+d8eL25y3Q7gOQQIolGtFujuHbXL1U3sfiFHIdeMM=
  bucket: whynotlang
  region: eu-west-1
  local-dir: artifacts
  skip_cleanup: true
  acl: public_read
  on:
    repo: pkedziora/whynotlang
